// FrontendDevelopment_HandsOn/Ranjani/Hands_On_8/task1/student-portal-vue/src/components/CourseCard.vue
<template>
  <div class="card">

    <h2>{{ name }}</h2>

    <p>Course Code: {{ code }}</p>

    <p>Credits: {{ credits }}</p>

    <p>Grade: {{ grade }}</p>

  </div>
</template>


<script setup>

defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String
})

</script>


<style scoped>

.card {
  border: 1px solid #ccc;
  padding: 15px;
  margin: 15px;
  border-radius: 10px;
}

</style>

// FrontendDevelopment_HandsOn/Ranjani/FrontendDevelopment_HandsOn/Ranjani/Hands_On_5/task1/src/components/CourseCard.jsx
function CourseCard(props){

    return(

        <div className="course-card">

            <h2>{props.name}</h2>

            <p>

                <strong>Code:</strong> {props.code}

            </p>

            <p>

                <strong>Credits:</strong> {props.credits}

            </p>

            <p>

                <strong>Grade:</strong> {props.grade}

            </p>

        </div>

    );

}

export default CourseCard;
