// FrontendDevelopment_HandsOn/Ranjani/Hands_On_8/task3/student-portal-vue/src/components/Header.vue
<template>

<header>

<h1>Student Portal</h1>

<p>
Enrolled Courses : {{ store.enrolledCourses.length }}
</p>

</header>

</template>

<script setup>

import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()

</script>

<style scoped>

header{

background:#42b883;
color:white;
padding:20px;
text-align:center;

}

</style>

// FrontendDevelopment_HandsOn/Ranjani/Hands_On_6/task2/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useContext } from "react";
import { EnrollmentContext } from "../context/EnrollmentContext";

function Header() {

  const { enrolledCourses } = useContext(EnrollmentContext);

  return (

    <header className="header">

      <h1>Student Portal</h1>

      <nav>

        <Link to="/">Home</Link>

        <Link to="/courses">Courses</Link>

        <Link to="/profile">Profile</Link>

      </nav>

      <h3>

        Enrolled Courses : {enrolledCourses.length}

      </h3>

    </header>

  );

}

export default Header;
