// FrontendDevelopment_HandsOn/Ranjani/Hands_On_8/task3/student-portal-vue/src/components/CourseCard.vue
<template>
  <div class="card">
    <h3>{{ course.name }}</h3>
    <p><strong>Code:</strong> {{ course.code }}</p>
    <p><strong>Credits:</strong> {{ course.credits }}</p>

    <button @click="$emit('enroll', course)">
      Enroll
    </button>
  </div>
</template>

<script setup>
defineProps({
  course: Object
})

defineEmits(['enroll'])
</script>

<style scoped>
.card{
  border:1px solid #ccc;
  border-radius:8px;
  padding:15px;
  margin:15px;
}

button{
  padding:8px 15px;
  cursor:pointer;
}
</style>

// FrontendDevelopment_HandsOn/Ranjani/FrontendDevelopment_HandsOn/Ranjani/Hands_On_5/task2/src/components/CourseCard.jsx
function CourseCard({

    id,

    name,

    code,

    credits,

    grade,

    onEnroll

}) {

    return (

        <div className="course-card">

            <h2>{name}</h2>

            <p>

                <strong>Code :</strong> {code}

            </p>

            <p>

                <strong>Credits :</strong> {credits}

            </p>

            <p>

                <strong>Grade :</strong> {grade}

            </p>

            <button

                onClick={() => onEnroll(id)}

            >

                Enroll

            </button>

        </div>

    );

}

export default CourseCard;
